run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - funlen
    - gochecknoglobals
    - dupl
    - wsl
    - gomnd
    - goerr113 
    - nestif
    - gofumpt
    - exhaustivestruct
    - paralleltest
    - gci
    - wrapcheck
    - cyclop
    - forcetypeassert
    - tagliatelle
    - gomoddirectives
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 50
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 100